#define DOWNLOADMAIDVERSION_1	0
#define DOWNLOADMAIDVERSION_2	1
#define DOWNLOADMAIDVERSION_3	0
#define DOWNLOADMAIDVERSION_4	2
#define DOWNLOADMAIDVERSION_NUMBER 0,1,0,2
#define DOWNLOADMAIDVERSION_STRING "0.1.0.2"
